### ISSUE TITLE
Gnome 3.32 compatibility

### ISSUE THREAD

**Issue by dasnoopy** [sustmi/gnome-shell-extension-workspace-switcher-popup-thumbnails#7] opened 2019-03-19 06:25 UTC
Any chance to make this nice extension compatible with latest gnome 3.32?
Currently, this error occurred when extension starts: 

`Extension "workspace-switcher-popup-thumbnails@sustmidown.centrum.cz" had error: Error: Type name Gjs_ThumbnailsBox is already registered`

Thanks

**Comment by sustmi** [comment] 2019-04-22 17:40
I am sorry, but I cannot reproduce the issue in GNOME Shell 3.30 and the v3.32 will be available in my distro in Fedora 30 which is going to be released in mid of May.
Unfortunately, I currently do not have the time to install some other distro with v3.32 in virtual machine and debug the issue.
I will look into it when Fedora releases GNOME Shell v3.32.
Thank you for your patience.

**Comment by sustmi** [comment] 2019-04-24 20:09
Hi @dasnoopy . I managed to update GNOME Shell in my Fedora to v3.32 using the packages from the yet-to-be-released Fedora 30. Now custom keyboard shortcuts stopped to work for me but I guess that is because I only updated GNOME Shell and not whole system. But that's another story...

Good news, I updated the extension to support GNOME Shell 3.32. Can you try `v3` (or current `master`) and confirm that it works for you?

**Comment by chrisjbillington** [comment] 2019-04-25 03:52
I can verify that v3 (assuming that's the latest on extensions.gnome.org) is working on gnome-shell 3.32.

There is a bug where it is not showing previews of other monitors, but I will report that separately.

**Comment by dasnoopy** [comment] 2019-04-25 05:21
@sustmi :  just to confirm that v3 downloaded from [release](https://github.com/sustmi/gnome-shell-extension-workspace-switcher-popup-thumbnails/releases) page works fine on my archlinux box with gnome 3.32.1 ...

many thanks

**Comment by sustmi** [comment] 2019-10-02 18:38
Thank you for testing the new version.

**Closed as completed by sustmi** 2019-10-02 18:38 UTC
